-- O código 40001 é retentável pelo cliente HTTP. Os invólucros convertem
-- conflitos otimistas em erro de domínio não retentável e identificável.
create or replace function public.salvar_diagnostico_ordem(p_ordem_id uuid,p_descricao text,p_observacoes text,p_previsao_em timestamptz,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.salvar_diagnostico_ordem_impl(p_ordem_id,p_descricao,p_observacoes,p_previsao_em,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.adicionar_item_ordem(p_ordem_id uuid,p_tipo text,p_servico_id uuid,p_descricao text,p_quantidade numeric,p_valor_unitario numeric,p_versao integer)
returns uuid language plpgsql security invoker set search_path = '' as $$ begin return private.adicionar_item_ordem_impl(p_ordem_id,p_tipo,p_servico_id,p_descricao,p_quantidade,p_valor_unitario,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.alterar_item_ordem(p_ordem_id uuid,p_item_id uuid,p_tipo text,p_servico_id uuid,p_descricao text,p_quantidade numeric,p_valor_unitario numeric,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.alterar_item_ordem_impl(p_ordem_id,p_item_id,p_tipo,p_servico_id,p_descricao,p_quantidade,p_valor_unitario,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.remover_item_ordem(p_ordem_id uuid,p_item_id uuid,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.remover_item_ordem_impl(p_ordem_id,p_item_id,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.aplicar_desconto_ordem(p_ordem_id uuid,p_desconto numeric,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.aplicar_desconto_ordem_impl(p_ordem_id,p_desconto,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.avancar_ordem_servico(p_ordem_id uuid,p_destino text,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.avancar_ordem_servico_impl(p_ordem_id,p_destino,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.registrar_aprovacao_item_ordem(p_ordem_id uuid,p_item_id uuid,p_decisao text,p_canal text,p_respondido_em timestamptz,p_observacoes text,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.registrar_aprovacao_item_ordem_impl(p_ordem_id,p_item_id,p_decisao,p_canal,p_respondido_em,p_observacoes,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.marcar_item_executado(p_ordem_id uuid,p_item_id uuid,p_executado boolean,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.marcar_item_executado_impl(p_ordem_id,p_item_id,p_executado,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.entregar_ordem_servico(p_ordem_id uuid,p_forma text,p_entregue_em timestamptz,p_observacoes text,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.entregar_ordem_servico_impl(p_ordem_id,p_forma,p_entregue_em,p_observacoes,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.cancelar_ordem_servico(p_ordem_id uuid,p_justificativa text,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.cancelar_ordem_servico_impl(p_ordem_id,p_justificativa,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.retroceder_ordem_servico(p_ordem_id uuid,p_destino text,p_justificativa text,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.retroceder_ordem_servico_impl(p_ordem_id,p_destino,p_justificativa,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
create or replace function public.reabrir_ordem_servico(p_ordem_id uuid,p_justificativa text,p_versao integer)
returns integer language plpgsql security invoker set search_path = '' as $$ begin return private.reabrir_ordem_servico_impl(p_ordem_id,p_justificativa,p_versao); exception when serialization_failure then raise exception 'CONFLITO_VERSAO: a ordem foi alterada por outro usuário.' using errcode = 'P0001'; end; $$;
